### ISSUE TITLE
Creation of dependencies file list

### ISSUE THREAD

**Issue by Park-Patrick** [INCF/bids-starter-kit#33]
Hi everyone!

The first thing that our users of the tutorials/scripts will need are the necessary software dependencies.

Some of them, like MATLAB, may already be familiar while others like Python libraries may require some more details (+ links to helpful installation sites).

Additionally, we will also require a `requirements.txt` file for eventual integration with Jupyter Notebooks and Binder.

@dorahermes @emdupre @KirstieJane , what are your thoughts?

I'd imagine this will be a growing list, but I am happy to start on it!

**Comment by dorahermes** [comment]
This sounds good. Even for the Matlab code there is already 1 dependency, because you need a json read and write package. This github site for this json/read/write package is listed on the wiki, but I have already had some people email me for a link so I think that something like this would be helpful.

**Comment by Park-Patrick** [comment]
Created the list in pull request #44. Let me know what you think!

**Comment by dorahermes** [comment]
It looks good. Octave is not quite a dependency of Matlab, so I am not sure whether I would list it under Matlab as a dependency, rather under "information:.." also have "open source equivalent:..."

**Comment by Park-Patrick** [comment]
Hey @dorahermes just clarified this in pull request #44. Let me know what you think!
