### ISSUE TITLE
Wiki does not support contributions from users without push access

### ISSUE THREAD

**Issue by chrisfilo** [INCF/bids-starter-kit#7]
Unlike contents of the repository [GitHub wiki does not support pull requests](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github). Workarounds exist, but seem to be cumbersome. This has [negative impact on new people wanting to contribute](https://twitter.com/DrMowinckels/status/946775322384568320).

Any ideas what to do instead? Series of Markdown documents? @dorahermes @KirstieJane @emdupre

**Comment by choldgraf** [comment]
Why not just make the wiki editable by anybody? Itd still record changes if something needed to be reverted, and is the most welcoming setup https://help.github.com/articles/changing-access-permissions-for-wikis/

**Comment by dorahermes** [comment]
Would this only open up the wiki? That sounds good.

**Comment by KirstieJane** [comment]
My vote would be for moving the wiki into markdown files in the repo itself - that way we can version control what’s going on easily, how tutorials change, who contributes etc.

I’m on holiday with no internet in our cabin (on a walk right now) but happy to contribute from Jan 2nd.

![Image](https://i.imgur.com/rPyrjZd.jpg)

**Comment by choldgraf** [comment]
@dorahermes yep I think that only applies to the wiki, so people still need to make PRs on the repo itself, but the wiki can be edited directly.

@KirstieJane I think that's a great point about history. Just a note that the wiki does support version control, edit history, etc (and it's all stored in markdown) e.g. [here's the home page history](https://github.com/INCF/bids-starter-kit/wiki/Home/_history). GitHub wikis are basically just a git repo with a more user-friendly interface, so I've got a slight preference for wikis as it reduces the barrier to contribution (and fits more readily into people's mental models of wikis in general)

**Comment by choldgraf** [comment]
also that photo looks charmingly wintery, solid postcard material right there :-)

**Comment by Athanasiamo** [comment]
I guess a publicly modifiable wiki would be the best option? Since it still stores history, it's easy for admins to revert changes is someone commits something not wanted? If the wiki can be made modifiable without the remaining repo being so? That's what I read from the instructions in the wiki, but I might be misunderstanding.

I also prefer keeping the wiki, instead of making a wiki out of markdowns within the repo it self. I like how it's "outside" the repo and not cluttering it.

**Comment by emdupre** [comment]
I've forked this discussion to #9, since it seems like it's moving beyond the original issue !

**Comment by dorahermes** [comment]
@chrisfilo @choldgraf do you see any big problems with opening up the wiki? 
We would need to set up an additional page on 'How to contribute to the wiki'.

**Comment by chrisfilo** [comment]
I don't see any downsides apart from potential spam bots (but I have not
seen those on GitHub, so it's unlikely).

Best,
Chris

**Comment by KirstieJane** [comment]
Happy new year everyone!!

This is going to be my last “anti-wiki” post - I think these are mostly my personal preferences, so we can totally disregard them!

Interestingly, my dislike of the wiki idea is exactly why @Athanasiamo likes them: they keep the documentation out of the “proper” repo. My personal opinion is that that makes contributions to documentation less “important” than code and devalues them. I think related to this point is the fact that contributors wouldn’t get any stats on the updates they provide. Not super important for GitHub super users, but very exciting for newbies!!

Also, I’ve never had much success getting people to edit wikis BUT I haven’t tried very hard!! If others on this thread feel the wiki has a lower barrier to entry than a pull request - and that we’d get those people contributing to this repo!! - I’m very happy to be convinced!

(For example, if YOU ALL prefer editing the wiki than the main repo, that totally counts.)

Another fun picture from my trip: 
![9c3b8700-6576-43b7-a60e-51758a1e831a](https://user-images.githubusercontent.com/3626306/34512325-a4e0405c-f059-11e7-8895-1c114643eb79.jpeg)

**Comment by Athanasiamo** [comment]
I think the wiki has a lower barrier to contribute to that the repo it self, but I might be overly cautious. But then, you would expect newbies to be extra cautious. It feels a little less intimidating contributing to a mass of md's alone, rather than editing md's within a repo with lots of other important stuff in it. At least for me. 

That being said, I really did expect the wiki to be pulled together with the entire repo when I made a clone/fork of it, so that was surprising (if you haven't guessed, I have not really worked with wiki's or cloned a repo with a wiki before, so I'm new to this part og github). And in that sense, the wiki may as well be stored in a wiki folder within the main repo, though you would loose part of the visual set-up github has for their wikis, which I like and find intuitive.

**Comment by Islast** [comment]
As a cautious user, what I like about working inside of github repos is the opportunity for pull requests. A pull request is me saying "I have made changes, please validate them before they go into the main branch". Editing a GitHub wiki I always fear that I'll make a mistake and nobody will ever notice.   
On the other hand, working inside of repos involves learning git and editing files (more intimidating than webpages for some reason).

Anyway it seems that we can't have both: the comfort of pull requests *and* the low barrier of not learning git. I think this decision needs to be based on who the contributors are.

**Comment by dorahermes** [comment]
Thank you all very much for sharing your thoughts! This is super helpful. We started the bids-starters-kit when explaining BIDS to a group of collaborators working with different code packages and different levels of git experience (none to a lot, from lab-managers to students and PIs). Everyone seemed to appreciate some brief description on how to start with BIDS (rather than reading through the pdf specs, or going through code). The first thing we needed here was a wiki that was brief and plain with just a few code snippets. However, the next thing that is required is a more extensive tutorial with more code, templates etc. Based on this, here's what I'll put on the repo readme:

------------
A community-curated collection of wikis, tutorials, and templates to get you started with creating BIDS compliant datasets.

The repository wiki: for first starters, brief text and code snippets to help start with BIDS. 

Tutorials: code and notebook-style tutorials on that help create a BIDS-compliant dataset.

Templates: template empty BIDS sidecar files.

If you have any questions, suggestions, etc please open an issue or make your own additions to the wiki or do a pull request to the code.
------------

**Comment by KirstieJane** [comment]
Looks good @dorahermes
